name: LaTeX compilation

on:
  push:
    branches:
      - developer
    paths:
      - '**/main.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # TeX Live 環境を準備
      - name: Install TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-pictures latexmk

      # 変更のあったディレクトリを検出
      - name: Detect changed directories
        id: changed
        run: |
          dirs=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'main\.tex' | xargs -r -n1 dirname | sort -u)
          echo "dirs=$dirs"
          echo "dirs=$dirs" >> $GITHUB_OUTPUT

      # 各ディレクトリで main.tex をコンパイル
      - name: Compile LaTeX in changed directories
        if: ${{ steps.changed.outputs.dirs != '' }}
        run: |
          for dir in ${{ steps.changed.outputs.dirs }}; do
            echo "Compiling $dir/main.tex ..."
            latexmk -pdf -cd "$dir/main.tex"
          done

      # 生成された PDF をコミットして同じブランチに push
      - name: Commit and push PDFs
        if: ${{ steps.changed.outputs.dirs != '' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add **/main.pdf
          git commit -m "Auto-compile main.pdf [skip ci]" || echo "No changes to commit"
          git push origin developer
